---
title: Cto Bro.Com
timezone: Europe/Paris
collections:
  call-to-action:
    title: Call To Action
    output: true
  footer:
    title: Footer
    output: true
  header:
    title: Header
    output: true
  languages:
    title: Languages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: page
  values:
    layout: default
- scope:
    path: home
    type: page
  values:
    layout: home
    Language: 
    SEO:
      Title: 
      Description: 
      Tags: 
    Header: 
    Footer: 
    Hero:
      Text: 
      Call To Action: 
    The offer:
      Text: 
      Body: 
      Call To Action: 
    Value Proposition:
      Text: 
      Body:
        -
      Call To Action: 
    The solution:
      Text: 
      Body: 
      Call To Action: 
    Testimonials:
      Text: 
      Body: 
      Call To Action: 
    How it works:
      Text: 
      Body: 
      Call To Action: 
    Audience:
      Text: 
      Body: 
      Call To Action: 
url: https://cto-bro.com
description: 
plugins:
- jekyll-sitemap
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"
permalink: "/articles/:year-:month/:title"
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
